using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Diamond.Common.Utilities
{
    public class FileType
    {

        public string key { get; set; }
        public string title { get; set; }
    }
    public static class FileTypes
    {
        public static List<FileType> types
        {
            get
            {
                return new List<FileType>
                { new FileType{ key = "3dm", title = "x-world/x-3dmf" }
,new FileType{key= "3dmf",title = "x-world/x-3dmf"}
,new FileType{key= "a",title = "application/octet-stream"}
,new FileType{key= "aab",title = "application/x-authorware-bin"}
,new FileType{key= "aam",title = "application/x-authorware-map"}
,new FileType{key= "aas",title = "application/x-authorware-seg"}
,new FileType{key= "abc",title = "text/vnd.abc"}
,new FileType{key= "acgi",title = "text/html"}
,new FileType{key= "afl",title = "video/animaflex"}
,new FileType{key= "ai",title = "application/postscript"}
,new FileType{key= "aif",title = "audio/aiff"}
,new FileType{key= "aif",title = "audio/x-aiff"}
,new FileType{key= "aifc",title = "audio/aiff"}
,new FileType{key= "aifc",title = "audio/x-aiff"}
,new FileType{key= "aiff",title = "audio/aiff"}
,new FileType{key= "aiff",title = "audio/x-aiff"}
,new FileType{key= "aim",title = "application/x-aim"}
,new FileType{key= "aip",title = "text/x-audiosoft-intra"}
,new FileType{key= "ani",title = "application/x-navi-animation"}
,new FileType{key= "aos",title = "application/x-nokia-9000-communicator-add-on-software"}
,new FileType{key= "aps",title = "application/mime"}
,new FileType{key= "arc",title = "application/octet-stream"}
,new FileType{key= "arj",title = "application/arj"}
,new FileType{key= "arj",title = "application/octet-stream"}
,new FileType{key= "art",title = "image/x-jg"}
,new FileType{key= "asf",title = "video/x-ms-asf"}
,new FileType{key= "asm",title = "text/x-asm"}
,new FileType{key= "asp",title = "text/asp"}
,new FileType{key= "asx",title = "application/x-mplayer2"}
,new FileType{key= "asx",title = "video/x-ms-asf"}
,new FileType{key= "asx",title = "video/x-ms-asf-plugin"}
,new FileType{key= "au",title = "audio/basic"}
,new FileType{key= "au",title = "audio/x-au"}
,new FileType{key= "avi",title = "application/x-troff-msvideo"}
,new FileType{key= "avi",title = "video/avi"}
,new FileType{key= "avi",title = "video/msvideo"}
,new FileType{key= "avi",title = "video/x-msvideo"}
,new FileType{key= "avs",title = "video/avs-video"}
,new FileType{key= "bcpio",title = "application/x-bcpio"}
,new FileType{key= "bin",title = "application/mac-binary"}
,new FileType{key= "bin",title = "application/macbinary"}
,new FileType{key= "bin",title = "application/octet-stream"}
,new FileType{key= "bin",title = "application/x-binary"}
,new FileType{key= "bin",title = "application/x-macbinary"}
,new FileType{key= "bm",title = "image/bmp"}
,new FileType{key= "bmp",title = "image/bmp"}
,new FileType{key= "bmp",title = "image/x-windows-bmp"}
,new FileType{key= "boo",title = "application/book"}
,new FileType{key= "book",title = "application/book"}
,new FileType{key= "boz",title = "application/x-bzip2"}
,new FileType{key= "bsh",title = "application/x-bsh"}
,new FileType{key= "bz",title = "application/x-bzip"}
,new FileType{key= "bz2",title = "application/x-bzip2"}
,new FileType{key= "c",title = "text/plain"}
,new FileType{key= "c",title = "text/x-c"}
,new FileType{key= "c++",title = "text/plain"}
,new FileType{key= "cat",title = "application/vnd.ms-pki.seccat"}
,new FileType{key= "cc",title = "text/plain"}
,new FileType{key= "cc",title = "text/x-c"}
,new FileType{key= "ccad",title = "application/clariscad"}
,new FileType{key= "cco",title = "application/x-cocoa"}
,new FileType{key= "cdf",title = "application/cdf"}
,new FileType{key= "cdf",title = "application/x-cdf"}
,new FileType{key= "cdf",title = "application/x-netcdf"}
,new FileType{key= "cer",title = "application/pkix-cert"}
,new FileType{key= "cer",title = "application/x-x509-ca-cert"}
,new FileType{key= "cha",title = "application/x-chat"}
,new FileType{key= "chat",title = "application/x-chat"}
,new FileType{key= "class",title = "application/java"}
,new FileType{key= "class",title = "application/java-byte-code"}
,new FileType{key= "class",title = "application/x-java-class"}
,new FileType{key= "com",title = "application/octet-stream"}
,new FileType{key= "com",title = "text/plain"}
,new FileType{key= "conf",title = "text/plain"}
,new FileType{key= "cpio",title = "application/x-cpio"}
,new FileType{key= "cpp",title = "text/x-c"}
,new FileType{key= "cpt",title = "application/mac-compactpro"}
,new FileType{key= "cpt",title = "application/x-compactpro"}
,new FileType{key= "cpt",title = "application/x-cpt"}
,new FileType{key= "crl",title = "application/pkcs-crl"}
,new FileType{key= "crl",title = "application/pkix-crl"}
,new FileType{key= "crt",title = "application/pkix-cert"}
,new FileType{key= "crt",title = "application/x-x509-ca-cert"}
,new FileType{key= "crt",title = "application/x-x509-user-cert"}
,new FileType{key= "csh",title = "application/x-csh"}
,new FileType{key= "csh",title = "text/x-script.csh"}
,new FileType{key= "css",title = "application/x-pointplus"}
,new FileType{key= "css",title = "text/css"}
,new FileType{key= "cxx",title = "text/plain"}
,new FileType{key= "dcr",title = "application/x-director"}
,new FileType{key= "deepv",title = "application/x-deepv"}
,new FileType{key= "def",title = "text/plain"}
,new FileType{key= "der",title = "application/x-x509-ca-cert"}
,new FileType{key= "dif",title = "video/x-dv"}
,new FileType{key= "dir",title = "application/x-director"}
,new FileType{key= "dl",title = "video/dl"}
,new FileType{key= "dl",title = "video/x-dl"}
,new FileType{key= "docx",title = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
,new FileType{key= "doc",title = "application/msword"}
,new FileType{key= "dot",title = "application/msword"}
,new FileType{key= "dp",title = "application/commonground"}
,new FileType{key= "drw",title = "application/drafting"}
,new FileType{key= "dump",title = "application/octet-stream"}
,new FileType{key= "dv",title = "video/x-dv"}
,new FileType{key= "dvi",title = "application/x-dvi"}
,new FileType{key= "dwf",title = "drawing/x-dwf (old)"}
,new FileType{key= "dwf",title = "model/vnd.dwf"}
,new FileType{key= "dwg",title = "application/acad"}
,new FileType{key= "dwg",title = "image/vnd.dwg"}
,new FileType{key= "dwg",title = "image/x-dwg"}
,new FileType{key= "dxf",title = "application/dxf"}
,new FileType{key= "dxf",title = "image/vnd.dwg"}
,new FileType{key= "dxf",title = "image/x-dwg"}
,new FileType{key= "dxr",title = "application/x-director"}
,new FileType{key= "el",title = "text/x-script.elisp"}
,new FileType{key= "elc",title = "application/x-bytecode.elisp (compiled elisp)"}
,new FileType{key= "elc",title = "application/x-elc"}
,new FileType{key= "env",title = "application/x-envoy"}
,new FileType{key= "eps",title = "application/postscript"}
,new FileType{key= "es",title = "application/x-esrehber"}
,new FileType{key= "etx",title = "text/x-setext"}
,new FileType{key= "evy",title = "application/envoy"}
,new FileType{key= "evy",title = "application/x-envoy"}
,new FileType{key= "exe",title = "application/octet-stream"}
,new FileType{key= "f",title = "text/plain"}
,new FileType{key= "f",title = "text/x-fortran"}
,new FileType{key= "f77",title = "text/x-fortran"}
,new FileType{key= "f90",title = "text/plain"}
,new FileType{key= "f90",title = "text/x-fortran"}
,new FileType{key= "fdf",title = "application/vnd.fdf"}
,new FileType{key= "fif",title = "application/fractals"}
,new FileType{key= "fif",title = "image/fif"}
,new FileType{key= "fli",title = "video/fli"}
,new FileType{key= "fli",title = "video/x-fli"}
,new FileType{key= "flo",title = "image/florian"}
,new FileType{key= "flx",title = "text/vnd.fmi.flexstor"}
,new FileType{key= "fmf",title = "video/x-atomic3d-feature"}
,new FileType{key= "for",title = "text/plain"}
,new FileType{key= "for",title = "text/x-fortran"}
,new FileType{key= "fpx",title = "image/vnd.fpx"}
,new FileType{key= "fpx",title = "image/vnd.net-fpx"}
,new FileType{key= "frl",title = "application/freeloader"}
,new FileType{key= "funk",title = "audio/make"}
,new FileType{key= "g",title = "text/plain"}
,new FileType{key= "g3",title = "image/g3fax"}
,new FileType{key= "gif",title = "image/gif"}
,new FileType{key= "gl",title = "video/gl"}
,new FileType{key= "gl",title = "video/x-gl"}
,new FileType{key= "gsd",title = "audio/x-gsm"}
,new FileType{key= "gsm",title = "audio/x-gsm"}
,new FileType{key= "gsp",title = "application/x-gsp"}
,new FileType{key= "gss",title = "application/x-gss"}
,new FileType{key= "gtar",title = "application/x-gtar"}
,new FileType{key= "gz",title = "application/x-compressed"}
,new FileType{key= "gz",title = "application/x-gzip"}
,new FileType{key= "gzip",title = "application/x-gzip"}
,new FileType{key= "gzip",title = "multipart/x-gzip"}
,new FileType{key= "h",title = "text/plain"}
,new FileType{key= "h",title = "text/x-h"}
,new FileType{key= "hdf",title = "application/x-hdf"}
,new FileType{key= "help",title = "application/x-help"}
,new FileType{key= "hgl",title = "application/vnd.hp-hpgl"}
,new FileType{key= "hh",title = "text/plain"}
,new FileType{key= "hh",title = "text/x-h"}
,new FileType{key= "hlb",title = "text/x-script"}
,new FileType{key= "hlp",title = "application/hlp"}
,new FileType{key= "hlp",title = "application/x-help"}
,new FileType{key= "hlp",title = "application/x-winhelp"}
,new FileType{key= "hpg",title = "application/vnd.hp-hpgl"}
,new FileType{key= "hpgl",title = "application/vnd.hp-hpgl"}
,new FileType{key= "hqx",title = "application/binhex"}
,new FileType{key= "hqx",title = "application/binhex4"}
,new FileType{key= "hqx",title = "application/mac-binhex"}
,new FileType{key= "hqx",title = "application/mac-binhex40"}
,new FileType{key= "hqx",title = "application/x-binhex40"}
,new FileType{key= "hqx",title = "application/x-mac-binhex40"}
,new FileType{key= "hta",title = "application/hta"}
,new FileType{key= "htc",title = "text/x-component"}
,new FileType{key= "htm",title = "text/html"}
,new FileType{key= "html",title = "text/html"}
,new FileType{key= "htmls",title = "text/html"}
,new FileType{key= "htt",title = "text/webviewhtml"}
,new FileType{key= "htx",title = "text/html"}
,new FileType{key= "ice",title = "x-conference/x-cooltalk"}
,new FileType{key= "ico",title = "image/x-icon"}
,new FileType{key= "idc",title = "text/plain"}
,new FileType{key= "ief",title = "image/ief"}
,new FileType{key= "iefs",title = "image/ief"}
,new FileType{key= "iges",title = "application/iges"}
,new FileType{key= "iges",title = "model/iges"}
,new FileType{key= "igs",title = "application/iges"}
,new FileType{key= "igs",title = "model/iges"}
,new FileType{key= "ima",title = "application/x-ima"}
,new FileType{key= "imap",title = "application/x-httpd-imap"}
,new FileType{key= "inf",title = "application/inf"}
,new FileType{key= "ins",title = "application/x-internett-signup"}
,new FileType{key= "ip",title = "application/x-ip2"}
,new FileType{key= "isu",title = "video/x-isvideo"}
,new FileType{key= "it",title = "audio/it"}
,new FileType{key= "iv",title = "application/x-inventor"}
,new FileType{key= "ivr",title = "i-world/i-vrml"}
,new FileType{key= "ivy",title = "application/x-livescreen"}
,new FileType{key= "jam",title = "audio/x-jam"}
,new FileType{key= "jav",title = "text/plain"}
,new FileType{key= "jav",title = "text/x-java-source"}
,new FileType{key= "java",title = "text/plain"}
,new FileType{key= "java",title = "text/x-java-source"}
,new FileType{key= "jcm",title = "application/x-java-commerce"}
,new FileType{key= "jfif",title = "image/jpeg"}
,new FileType{key= "jfif",title = "image/pjpeg"}
,new FileType{key= "jfif-tbnl",title = "image/jpeg"}
,new FileType{key= "jpe",title = "image/jpeg"}
,new FileType{key= "jpe",title = "image/pjpeg"}
,new FileType{key= "jpeg",title = "image/jpeg"}
,new FileType{key= "jpeg",title = "image/pjpeg"}
,new FileType{key= "jpg",title = "image/jpeg"}
,new FileType{key= "jpg",title = "image/pjpeg"}
,new FileType{key= "jps",title = "image/x-jps"}
,new FileType{key= "js",title = "application/x-javascript"}
,new FileType{key= "js",title = "application/javascript"}
,new FileType{key= "js",title = "application/ecmascript"}
,new FileType{key= "js",title = "text/javascript"}
,new FileType{key= "js",title = "text/ecmascript"}
,new FileType{key= "jut",title = "image/jutvision"}
,new FileType{key= "kar",title = "audio/midi"}
,new FileType{key= "kar",title = "music/x-karaoke"}
,new FileType{key= "ksh",title = "application/x-ksh"}
,new FileType{key= "ksh",title = "text/x-script.ksh"}
,new FileType{key= "la",title = "audio/nspaudio"}
,new FileType{key= "la",title = "audio/x-nspaudio"}
,new FileType{key= "lam",title = "audio/x-liveaudio"}
,new FileType{key= "latex",title = "application/x-latex"}
,new FileType{key= "lha",title = "application/lha"}
,new FileType{key= "lha",title = "application/octet-stream"}
,new FileType{key= "lha",title = "application/x-lha"}
,new FileType{key= "lhx",title = "application/octet-stream"}
,new FileType{key= "list",title = "text/plain"}
,new FileType{key= "lma",title = "audio/nspaudio"}
,new FileType{key= "lma",title = "audio/x-nspaudio"}
,new FileType{key= "log",title = "text/plain"}
,new FileType{key= "lsp",title = "application/x-lisp"}
,new FileType{key= "lsp",title = "text/x-script.lisp"}
,new FileType{key= "lst",title = "text/plain"}
,new FileType{key= "lsx",title = "text/x-la-asf"}
,new FileType{key= "ltx",title = "application/x-latex"}
,new FileType{key= "lzh",title = "application/octet-stream"}
,new FileType{key= "lzh",title = "application/x-lzh"}
,new FileType{key= "lzx",title = "application/lzx"}
,new FileType{key= "lzx",title = "application/octet-stream"}
,new FileType{key= "lzx",title = "application/x-lzx"}
,new FileType{key= "m",title = "text/plain"}
,new FileType{key= "m",title = "text/x-m"}
,new FileType{key= "m1v",title = "video/mpeg"}
,new FileType{key= "m2a",title = "audio/mpeg"}
,new FileType{key= "m2v",title = "video/mpeg"}
,new FileType{key= "m3u",title = "audio/x-mpequrl"}
,new FileType{key= "man",title = "application/x-troff-man"}
,new FileType{key= "map",title = "application/x-navimap"}
,new FileType{key= "mar",title = "text/plain"}
,new FileType{key= "mbd",title = "application/mbedlet"}
,new FileType{key= "mc$",title = "application/x-magic-cap-package-1.0"}
,new FileType{key= "mcd",title = "application/mcad"}
,new FileType{key= "mcd",title = "application/x-mathcad"}
,new FileType{key= "mcf",title = "image/vasa"}
,new FileType{key= "mcf",title = "text/mcf"}
,new FileType{key= "mcp",title = "application/netmc"}
,new FileType{key= "me",title = "application/x-troff-me"}
,new FileType{key= "mht",title = "message/rfc822"}
,new FileType{key= "mhtml",title = "message/rfc822"}
,new FileType{key= "mid",title = "application/x-midi"}
,new FileType{key= "mid",title = "audio/midi"}
,new FileType{key= "mid",title = "audio/x-mid"}
,new FileType{key= "mid",title = "audio/x-midi"}
,new FileType{key= "mid",title = "music/crescendo"}
,new FileType{key= "mid",title = "x-music/x-midi"}
,new FileType{key= "midi",title = "application/x-midi"}
,new FileType{key= "midi",title = "audio/midi"}
,new FileType{key= "midi",title = "audio/x-mid"}
,new FileType{key= "midi",title = "audio/x-midi"}
,new FileType{key= "midi",title = "music/crescendo"}
,new FileType{key= "midi",title = "x-music/x-midi"}
,new FileType{key= "mif",title = "application/x-frame"}
,new FileType{key= "mif",title = "application/x-mif"}
,new FileType{key= "mime",title = "message/rfc822"}
,new FileType{key= "mime",title = "www/mime"}
,new FileType{key= "mjf",title = "audio/x-vnd.audioexplosion.mjuicemedia"}
,new FileType{key= "mjpg",title = "video/x-motion-jpeg"}
,new FileType{key= "mm",title = "application/base64"}
,new FileType{key= "mm",title = "application/x-meme"}
,new FileType{key= "mme",title = "application/base64"}
,new FileType{key= "mod",title = "audio/mod"}
,new FileType{key= "mod",title = "audio/x-mod"}
,new FileType{key= "moov",title = "video/quicktime"}
,new FileType{key= "mov",title = "video/quicktime"}
,new FileType{key= "movie",title = "video/x-sgi-movie"}
,new FileType{key= "mp2",title = "audio/mpeg"}
,new FileType{key= "mp2",title = "audio/x-mpeg"}
,new FileType{key= "mp2",title = "video/mpeg"}
,new FileType{key= "mp2",title = "video/x-mpeg"}
,new FileType{key= "mp2",title = "video/x-mpeq2a"}
,new FileType{key= "mp3",title = "audio/mpeg3"}
,new FileType{key= "mp3",title = "audio/x-mpeg-3"}
,new FileType{key= "mp3",title = "video/mpeg"}
,new FileType{key= "mp3",title = "video/x-mpeg"}
,new FileType{key= "mpa",title = "audio/mpeg"}
,new FileType{key= "mpa",title = "video/mpeg"}
,new FileType{key= "mpc",title = "application/x-project"}
,new FileType{key= "mpe",title = "video/mpeg"}
,new FileType{key= "mpeg",title = "video/mpeg"}
,new FileType{key= "mpg",title = "audio/mpeg"}
,new FileType{key= "mpg",title = "video/mpeg"}
,new FileType{key= "mpga",title = "audio/mpeg"}
,new FileType{key= "mpp",title = "application/vnd.ms-project"}
,new FileType{key= "mpt",title = "application/x-project"}
,new FileType{key= "mpv",title = "application/x-project"}
,new FileType{key= "mpx",title = "application/x-project"}
,new FileType{key= "mrc",title = "application/marc"}
,new FileType{key= "ms",title = "application/x-troff-ms"}
,new FileType{key= "mv",title = "video/x-sgi-movie"}
,new FileType{key= "my",title = "audio/make"}
,new FileType{key= "mzz",title = "application/x-vnd.audioexplosion.mzz"}
,new FileType{key= "nap",title = "image/naplps"}
,new FileType{key= "naplps",title = "image/naplps"}
,new FileType{key= "nc",title = "application/x-netcdf"}
,new FileType{key= "ncm",title = "application/vnd.nokia.configuration-message"}
,new FileType{key= "nif",title = "image/x-niff"}
,new FileType{key= "niff",title = "image/x-niff"}
,new FileType{key= "nix",title = "application/x-mix-transfer"}
,new FileType{key= "nsc",title = "application/x-conference"}
,new FileType{key= "nvd",title = "application/x-navidoc"}
,new FileType{key= "o",title = "application/octet-stream"}
,new FileType{key= "oda",title = "application/oda"}
,new FileType{key= "omc",title = "application/x-omc"}
,new FileType{key= "omcd",title = "application/x-omcdatamaker"}
,new FileType{key= "omcr",title = "application/x-omcregerator"}
,new FileType{key= "p",title = "text/x-pascal"}
,new FileType{key= "p10",title = "application/pkcs10"}
,new FileType{key= "p10",title = "application/x-pkcs10"}
,new FileType{key= "p12",title = "application/pkcs-12"}
,new FileType{key= "p12",title = "application/x-pkcs12"}
,new FileType{key= "p7a",title = "application/x-pkcs7-signature"}
,new FileType{key= "p7c",title = "application/pkcs7-mime"}
,new FileType{key= "p7c",title = "application/x-pkcs7-mime"}
,new FileType{key= "p7m",title = "application/pkcs7-mime"}
,new FileType{key= "p7m",title = "application/x-pkcs7-mime"}
,new FileType{key= "p7r",title = "application/x-pkcs7-certreqresp"}
,new FileType{key= "p7s",title = "application/pkcs7-signature"}
,new FileType{key= "part",title = "application/pro_eng"}
,new FileType{key= "pas",title = "text/pascal"}
,new FileType{key= "pbm",title = "image/x-portable-bitmap"}
,new FileType{key= "pcl",title = "application/vnd.hp-pcl"}
,new FileType{key= "pcl",title = "application/x-pcl"}
,new FileType{key= "pct",title = "image/x-pict"}
,new FileType{key= "pcx",title = "image/x-pcx"}
,new FileType{key= "pdb",title = "chemical/x-pdb"}
,new FileType{key= "pdf",title = "application/pdf"}
,new FileType{key= "pfunk",title = "audio/make"}
,new FileType{key= "pfunk",title = "audio/make.my.funk"}
,new FileType{key= "pgm",title = "image/x-portable-graymap"}
,new FileType{key= "pgm",title = "image/x-portable-greymap"}
,new FileType{key= "pic",title = "image/pict"}
,new FileType{key= "pict",title = "image/pict"}
,new FileType{key= "pkg",title = "application/x-newton-compatible-pkg"}
,new FileType{key= "pko",title = "application/vnd.ms-pki.pko"}
,new FileType{key= "pl",title = "text/plain"}
,new FileType{key= "pl",title = "text/x-script.perl"}
,new FileType{key= "plx",title = "application/x-pixclscript"}
,new FileType{key= "pm",title = "image/x-xpixmap"}
,new FileType{key= "pm",title = "text/x-script.perl-module"}
,new FileType{key= "pm4",title = "application/x-pagemaker"}
,new FileType{key= "pm5",title = "application/x-pagemaker"}
,new FileType{key= "png",title = "image/png"}
,new FileType{key= "pnm",title = "application/x-portable-anymap"}
,new FileType{key= "pnm",title = "image/x-portable-anymap"}
,new FileType{key= "pot",title = "application/mspowerpoint"}
,new FileType{key= "pot",title = "application/vnd.ms-powerpoint"}
,new FileType{key= "pov",title = "model/x-pov"}
,new FileType{key= "ppa",title = "application/vnd.ms-powerpoint"}
,new FileType{key= "ppm",title = "image/x-portable-pixmap"}
,new FileType{key= "pps",title = "application/mspowerpoint"}
,new FileType{key= "pps",title = "application/vnd.ms-powerpoint"}
,new FileType{key= "ppt",title = "application/mspowerpoint"}
,new FileType{key= "ppt",title = "application/powerpoint"}
,new FileType{key= "ppt",title = "application/vnd.ms-powerpoint"}
,new FileType{key= "ppt",title = "application/x-mspowerpoint"}
,new FileType{key= "ppz",title = "application/mspowerpoint"}
,new FileType{key= "pre",title = "application/x-freelance"}
,new FileType{key= "prt",title = "application/pro_eng"}
,new FileType{key= "ps",title = "application/postscript"}
,new FileType{key= "psd",title = "application/octet-stream"}
,new FileType{key= "pvu",title = "paleovu/x-pv"}
,new FileType{key= "pwz",title = "application/vnd.ms-powerpoint"}
,new FileType{key= "py",title = "text/x-script.phyton"}
,new FileType{key= "pyc",title = "application/x-bytecode.python"}
,new FileType{key= "qcp",title = "audio/vnd.qcelp"}
,new FileType{key= "qd3",title = "x-world/x-3dmf"}
,new FileType{key= "qd3d",title = "x-world/x-3dmf"}
,new FileType{key= "qif",title = "image/x-quicktime"}
,new FileType{key= "qt",title = "video/quicktime"}
,new FileType{key= "qtc",title = "video/x-qtc"}
,new FileType{key= "qti",title = "image/x-quicktime"}
,new FileType{key= "qtif",title = "image/x-quicktime"}
,new FileType{key= "ra",title = "audio/x-pn-realaudio"}
,new FileType{key= "ra",title = "audio/x-pn-realaudio-plugin"}
,new FileType{key= "ra",title = "audio/x-realaudio"}
,new FileType{key= "ram",title = "audio/x-pn-realaudio"}
,new FileType{key= "ras",title = "application/x-cmu-raster"}
,new FileType{key= "ras",title = "image/cmu-raster"}
,new FileType{key= "ras",title = "image/x-cmu-raster"}
,new FileType{key= "rast",title = "image/cmu-raster"}
,new FileType{key= "rexx",title = "text/x-script.rexx"}
,new FileType{key= "rf",title = "image/vnd.rn-realflash"}
,new FileType{key= "rgb",title = "image/x-rgb"}
,new FileType{key= "rm",title = "application/vnd.rn-realmedia"}
,new FileType{key= "rm",title = "audio/x-pn-realaudio"}
,new FileType{key= "rmi",title = "audio/mid"}
,new FileType{key= "rmm",title = "audio/x-pn-realaudio"}
,new FileType{key= "rmp",title = "audio/x-pn-realaudio"}
,new FileType{key= "rmp",title = "audio/x-pn-realaudio-plugin"}
,new FileType{key= "rng",title = "application/ringing-tones"}
,new FileType{key= "rng",title = "application/vnd.nokia.ringing-tone"}
,new FileType{key= "rnx",title = "application/vnd.rn-realplayer"}
,new FileType{key= "roff",title = "application/x-troff"}
,new FileType{key= "rp",title = "image/vnd.rn-realpix"}
,new FileType{key= "rpm",title = "audio/x-pn-realaudio-plugin"}
,new FileType{key= "rt",title = "text/richtext"}
,new FileType{key= "rt",title = "text/vnd.rn-realtext"}
,new FileType{key= "rtf",title = "application/rtf"}
,new FileType{key= "rtf",title = "application/x-rtf"}
,new FileType{key= "rtf",title = "text/richtext"}
,new FileType{key= "rtx",title = "application/rtf"}
,new FileType{key= "rtx",title = "text/richtext"}
,new FileType{key= "rv",title = "video/vnd.rn-realvideo"}
,new FileType{key= "s",title = "text/x-asm"}
,new FileType{key= "s3m",title = "audio/s3m"}
,new FileType{key= "saveme",title = "application/octet-stream"}
,new FileType{key= "sbk",title = "application/x-tbook"}
,new FileType{key= "scm",title = "application/x-lotusscreencam"}
,new FileType{key= "scm",title = "text/x-script.guile"}
,new FileType{key= "scm",title = "text/x-script.scheme"}
,new FileType{key= "scm",title = "video/x-scm"}
,new FileType{key= "sdml",title = "text/plain"}
,new FileType{key= "sdp",title = "application/sdp"}
,new FileType{key= "sdp",title = "application/x-sdp"}
,new FileType{key= "sdr",title = "application/sounder"}
,new FileType{key= "sea",title = "application/sea"}
,new FileType{key= "sea",title = "application/x-sea"}
,new FileType{key= "set",title = "application/set"}
,new FileType{key= "sgm",title = "text/sgml"}
,new FileType{key= "sgm",title = "text/x-sgml"}
,new FileType{key= "sgml",title = "text/sgml"}
,new FileType{key= "sgml",title = "text/x-sgml"}
,new FileType{key= "sh",title = "application/x-bsh"}
,new FileType{key= "sh",title = "application/x-sh"}
,new FileType{key= "sh",title = "application/x-shar"}
,new FileType{key= "sh",title = "text/x-script.sh"}
,new FileType{key= "shar",title = "application/x-bsh"}
,new FileType{key= "shar",title = "application/x-shar"}
,new FileType{key= "shtml",title = "text/html"}
,new FileType{key= "shtml",title = "text/x-server-parsed-html"}
,new FileType{key= "sid",title = "audio/x-psid"}
,new FileType{key= "sit",title = "application/x-sit"}
,new FileType{key= "sit",title = "application/x-stuffit"}
,new FileType{key= "skd",title = "application/x-koan"}
,new FileType{key= "skm",title = "application/x-koan"}
,new FileType{key= "skp",title = "application/x-koan"}
,new FileType{key= "skt",title = "application/x-koan"}
,new FileType{key= "sl",title = "application/x-seelogo"}
,new FileType{key= "smi",title = "application/smil"}
,new FileType{key= "smil",title = "application/smil"}
,new FileType{key= "snd",title = "audio/basic"}
,new FileType{key= "snd",title = "audio/x-adpcm"}
,new FileType{key= "sol",title = "application/solids"}
,new FileType{key= "spc",title = "application/x-pkcs7-certificates"}
,new FileType{key= "spc",title = "text/x-speech"}
,new FileType{key= "spl",title = "application/futuresplash"}
,new FileType{key= "spr",title = "application/x-sprite"}
,new FileType{key= "sprite",title = "application/x-sprite"}
,new FileType{key= "src",title = "application/x-wais-source"}
,new FileType{key= "ssi",title = "text/x-server-parsed-html"}
,new FileType{key= "ssm",title = "application/streamingmedia"}
,new FileType{key= "sst",title = "application/vnd.ms-pki.certstore"}
,new FileType{key= "step",title = "application/step"}
,new FileType{key= "stl",title = "application/sla"}
,new FileType{key= "stl",title = "application/vnd.ms-pki.stl"}
,new FileType{key= "stl",title = "application/x-navistyle"}
,new FileType{key= "stp",title = "application/step"}
,new FileType{key= "sv4cpio",title = "application/x-sv4cpio"}
,new FileType{key= "sv4crc",title = "application/x-sv4crc"}
,new FileType{key= "svf",title = "image/vnd.dwg"}
,new FileType{key= "svf",title = "image/x-dwg"}
,new FileType{key= "svr",title = "application/x-world"}
,new FileType{key= "svr",title = "x-world/x-svr"}
,new FileType{key= "swf",title = "application/x-shockwave-flash"}
,new FileType{key= "t",title = "application/x-troff"}
,new FileType{key= "talk",title = "text/x-speech"}
,new FileType{key= "tar",title = "application/x-tar"}
,new FileType{key= "tbk",title = "application/toolbook"}
,new FileType{key= "tbk",title = "application/x-tbook"}
,new FileType{key= "tcl",title = "application/x-tcl"}
,new FileType{key= "tcl",title = "text/x-script.tcl"}
,new FileType{key= "tcsh",title = "text/x-script.tcsh"}
,new FileType{key= "tex",title = "application/x-tex"}
,new FileType{key= "texi",title = "application/x-texinfo"}
,new FileType{key= "texinfo",title = "application/x-texinfo"}
,new FileType{key= "text",title = "application/plain"}
,new FileType{key= "text",title = "text/plain"}
,new FileType{key= "tgz",title = "application/gnutar"}
,new FileType{key= "tgz",title = "application/x-compressed"}
,new FileType{key= "tif",title = "image/tiff"}
,new FileType{key= "tif",title = "image/x-tiff"}
,new FileType{key= "tiff",title = "image/tiff"}
,new FileType{key= "tiff",title = "image/x-tiff"}
,new FileType{key= "tr",title = "application/x-troff"}
,new FileType{key= "tsi",title = "audio/tsp-audio"}
,new FileType{key= "tsp",title = "application/dsptype"}
,new FileType{key= "tsp",title = "audio/tsplayer"}
,new FileType{key= "tsv",title = "text/tab-separated-values"}
,new FileType{key= "turbot",title = "image/florian"}
,new FileType{key= "txt",title = "text/plain"}
,new FileType{key= "uil",title = "text/x-uil"}
,new FileType{key= "uni",title = "text/uri-list"}
,new FileType{key= "unis",title = "text/uri-list"}
,new FileType{key= "unv",title = "application/i-deas"}
,new FileType{key= "uri",title = "text/uri-list"}
,new FileType{key= "uris",title = "text/uri-list"}
,new FileType{key= "ustar",title = "application/x-ustar"}
,new FileType{key= "ustar",title = "multipart/x-ustar"}
,new FileType{key= "uu",title = "application/octet-stream"}
,new FileType{key= "uu",title = "text/x-uuencode"}
,new FileType{key= "uue",title = "text/x-uuencode"}
,new FileType{key= "vcd",title = "application/x-cdlink"}
,new FileType{key= "vcs",title = "text/x-vcalendar"}
,new FileType{key= "vda",title = "application/vda"}
,new FileType{key= "vdo",title = "video/vdo"}
,new FileType{key= "vew",title = "application/groupwise"}
,new FileType{key= "viv",title = "video/vivo"}
,new FileType{key= "viv",title = "video/vnd.vivo"}
,new FileType{key= "vivo",title = "video/vivo"}
,new FileType{key= "vivo",title = "video/vnd.vivo"}
,new FileType{key= "vmd",title = "application/vocaltec-media-desc"}
,new FileType{key= "vmf",title = "application/vocaltec-media-"}
,new FileType{key= "voc",title = "audio/voc"}
,new FileType{key= "voc",title = "audio/x-voc"}
,new FileType{key= "vos",title = "video/vosaic"}
,new FileType{key= "vox",title = "audio/voxware"}
,new FileType{key= "vqe",title = "audio/x-twinvq-plugin"}
,new FileType{key= "vqf",title = "audio/x-twinvq"}
,new FileType{key= "vql",title = "audio/x-twinvq-plugin"}
,new FileType{key= "vrml",title = "application/x-vrml"}
,new FileType{key= "vrml",title = "model/vrml"}
,new FileType{key= "vrml",title = "x-world/x-vrml"}
,new FileType{key= "vrt",title = "x-world/x-vrt"}
,new FileType{key= "vsd",title = "application/x-visio"}
,new FileType{key= "vst",title = "application/x-visio"}
,new FileType{key= "vsw",title = "application/x-visio"}
,new FileType{key= "w60",title = "application/wordperfect6.0"}
,new FileType{key= "w61",title = "application/wordperfect6.1"}
,new FileType{key= "w6w",title = "application/msword"}
,new FileType{key= "wav",title = "audio/wav"}
,new FileType{key= "wav",title = "audio/x-wav"}
,new FileType{key= "wb1",title = "application/x-qpro"}
,new FileType{key= "wbmp",title = "image/vnd.wap.wbmp"}
,new FileType{key= "web",title = "application/vnd.xara"}
,new FileType{key= "wiz",title = "application/msword"}
,new FileType{key= "wk1",title = "application/x-123"}
,new FileType{key= "wmf",title = "windows/meta"}
,new FileType{key= "wml",title = "text/vnd.wap.wml"}
,new FileType{key= "wmlc",title = "application/vnd.wap.wmlc"}
,new FileType{key= "wmls",title = "text/vnd.wap.wmlscript"}
,new FileType{key= "wmlsc",title = "application/vnd.wap.wmlscriptc"}
,new FileType{key= "word",title = "application/msword"}
,new FileType{key= "wp",title = "application/wordperfect"}
,new FileType{key= "wp5",title = "application/wordperfect"}
,new FileType{key= "wp5",title = "application/wordperfect6.0"}
,new FileType{key= "wp6",title = "application/wordperfect"}
,new FileType{key= "wpd",title = "application/wordperfect"}
,new FileType{key= "wpd",title = "application/x-wpwin"}
,new FileType{key= "wq1",title = "application/x-lotus"}
,new FileType{key= "wri",title = "application/mswrite"}
,new FileType{key= "wri",title = "application/x-wri"}
,new FileType{key= "wrl",title = "application/x-world"}
,new FileType{key= "wrl",title = "model/vrml"}
,new FileType{key= "wrl",title = "x-world/x-vrml"}
,new FileType{key= "wrz",title = "model/vrml"}
,new FileType{key= "wrz",title = "x-world/x-vrml"}
,new FileType{key= "wsc",title = "text/scriplet"}
,new FileType{key= "wsrc",title = "application/x-wais-source"}
,new FileType{key= "wtk",title = "application/x-wintalk"}
,new FileType{key= "xbm",title = "image/x-xbitmap"}
,new FileType{key= "xbm",title = "image/x-xbm"}
,new FileType{key= "xbm",title = "image/xbm"}
,new FileType{key= "xdr",title = "video/x-amt-demorun"}
,new FileType{key= "xgz",title = "xgl/drawing"}
,new FileType{key= "xif",title = "image/vnd.xiff"}
,new FileType{key= "xl",title = "application/excel"}
,new FileType{key= "xla",title = "application/excel"}
,new FileType{key= "xla",title = "application/x-excel"}
,new FileType{key= "xla",title = "application/x-msexcel"}
,new FileType{key= "xlb",title = "application/excel"}
,new FileType{key= "xlb",title = "application/vnd.ms-excel"}
,new FileType{key= "xlb",title = "application/x-excel"}
,new FileType{key= "xlc",title = "application/excel"}
,new FileType{key= "xlc",title = "application/vnd.ms-excel"}
,new FileType{key= "xlc",title = "application/x-excel"}
,new FileType{key= "xld",title = "application/excel"}
,new FileType{key= "xld",title = "application/x-excel"}
,new FileType{key= "xlk",title = "application/excel"}
,new FileType{key= "xlk",title = "application/x-excel"}
,new FileType{key= "xll",title = "application/excel"}
,new FileType{key= "xll",title = "application/vnd.ms-excel"}
,new FileType{key= "xll",title = "application/x-excel"}
,new FileType{key= "xlm",title = "application/excel"}
,new FileType{key= "xlm",title = "application/vnd.ms-excel"}
,new FileType{key= "xlm",title = "application/x-excel"}
,new FileType{key= "xls",title = "application/excel"}
,new FileType{key= "xls",title = "application/vnd.ms-excel"}
,new FileType{key= "xls",title = "application/x-excel"}
,new FileType{key= "xls",title = "application/x-msexcel"}
,new FileType{key= "xlt",title = "application/excel"}
,new FileType{key= "xlt",title = "application/x-excel"}
,new FileType{key= "xlv",title = "application/excel"}
,new FileType{key= "xlv",title = "application/x-excel"}
,new FileType{key= "xlw",title = "application/excel"}
,new FileType{key= "xlw",title = "application/vnd.ms-excel"}
,new FileType{key= "xlw",title = "application/x-excel"}
,new FileType{key= "xlw",title = "application/x-msexcel"}
,new FileType{key= "xm",title = "audio/xm"}
,new FileType{key= "xml",title = "application/xml"}
,new FileType{key= "xml",title = "text/xml"}
,new FileType{key= "xmz",title = "xgl/movie"}
,new FileType{key= "xpix",title = "application/x-vnd.ls-xpix"}
,new FileType{key= "xpm",title = "image/x-xpixmap"}
,new FileType{key= "xpm",title = "image/xpm"}
,new FileType{key= "x-png",title = "image/png"}
,new FileType{key= "xsr",title = "video/x-amt-showrun"}
,new FileType{key= "xwd",title = "image/x-xwd"}
,new FileType{key= "xwd",title = "image/x-xwindowdump"}
,new FileType{key= "xyz",title = "chemical/x-pdb"}
,new FileType{key= "z",title = "application/x-compress"}
,new FileType{key= "z",title = "application/x-compressed"}
,new FileType{key= "zip",title = "application/x-compressed"}
,new FileType{key= "zip",title = "application/x-zip-compressed"}
,new FileType{key= "zip",title = "application/zip"}
,new FileType{key= "zip",title = "multipart/x-zip"}
,new FileType{key= "zoo",title = "application/octet-stream"}
,new FileType{key= "zsh",title = "text/x-script.zsh"}
            };
            }

        }
    }
}
